name: Create VPS (Auto Restart)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [create-vps]

env:
  VPS_NAME: vps-project-1757284306519
  TMATE_SERVER: nyc1.tmate.io
  GITHUB_TOKEN_VPS: ${{ secrets.GH_TOKEN }}
  NGROK_SERVER_URL: https://vps-github-datlohehe.vercel.app

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: write
      actions: write

    steps:
    - name: ⬇️ Checkout source
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: 🐍 Tạo file VPS info
      run: |
        mkdir -Force links
        "VPS khởi tạo - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" | Out-File -FilePath "links/vps-project-1757284306519.txt" -Encoding UTF8

    - name: 🖥️ Cài đặt và chạy TightVNC, noVNC, Cloudflared
  shell: pwsh
  run: |
    Write-Host "📥 Installing TightVNC, noVNC, and Cloudflared..."
    
    try {
      # ... (phần cài đặt TightVNC giữ nguyên)
      
      Write-Host "📥 Installing Python dependencies for noVNC and websockify..."
      # ... (phần cài đặt pip giữ nguyên)
      
      Write-Host "🔍 Checking noVNC installation via pip..."
      try {
        $novncInfo = pip show novnc
        Write-Host "📜 noVNC package info:"
        Write-Host $novncInfo
        $novncPath = ($novncInfo | Select-String "Location: (.*)").Matches.Groups[1].Value + "\novnc"
        if (Test-Path "$novncPath") {
          dir $novncPath -Recurse | Write-Host
          if (-not (Test-Path "$novncPath/vnc.html")) {
            Write-Host "❌ noVNC directory is incomplete, vnc.html not found"
            Write-Host "🔄 Falling back to GitHub download..."
            $maxDownloadAttempts = 5
            for ($i = 1; $i -le $maxDownloadAttempts; $i++) {
              try {
                Write-Host "📥 Downloading custom noVNC from Cudatto1m (attempt $i/$maxDownloadAttempts)..."
                Remove-Item -Recurse -Force noVNC -ErrorAction SilentlyContinue
                $novncUrl = "https://github.com/Cudatto1m/noVNC-Custom/archive/refs/heads/master.zip"
                Write-Host "🔗 Using URL: $novncUrl"
                $response = Invoke-WebRequest -Uri $novncUrl -OutFile "noVNC.zip" -TimeoutSec 60 -PassThru
                Write-Host "ℹ️ HTTP Status: $($response.StatusCode) $($response.StatusDescription)"
                Expand-Archive -Path "noVNC.zip" -DestinationPath "." -Force
                Move-Item -Path "noVNC-Custom-master" -Destination "noVNC" -Force
                Write-Host "✅ Custom noVNC downloaded and extracted"
                $novncPath = "noVNC"
                break
              } catch {
                Write-Host "⚠️ Custom noVNC download attempt $i/$maxDownloadAttempts failed: $_"
                if ($i -eq $maxDownloadAttempts) {
                  Write-Host "❌ Failed to download custom noVNC"
                  exit 1
                }
                Start-Sleep -Seconds 10
              }
            }
          }
        } else {
          Write-Host "❌ noVNC directory does not exist, downloading custom noVNC..."
          $maxDownloadAttempts = 5
          for ($i = 1; $i -le $maxDownloadAttempts; $i++) {
            try {
              Write-Host "📥 Downloading custom noVNC from Cudatto1m (attempt $i/$maxDownloadAttempts)..."
              Remove-Item -Recurse -Force noVNC -ErrorAction SilentlyContinue
              $novncUrl = "https://github.com/Cudatto1m/noVNC-Custom/archive/refs/heads/master.zip"
              Write-Host "🔗 Using URL: $novncUrl"
              $response = Invoke-WebRequest -Uri $novncUrl -OutFile "noVNC.zip" -TimeoutSec 60 -PassThru
              Write-Host "ℹ️ HTTP Status: $($response.StatusCode) $($response.StatusDescription)"
              Expand-Archive -Path "noVNC.zip" -DestinationPath "." -Force
              Move-Item -Path "noVNC-Custom-master" -Destination "noVNC" -Force
              Write-Host "✅ Custom noVNC downloaded and extracted"
              $novncPath = "noVNC"
              break
            } catch {
              Write-Host "⚠️ Custom noVNC download attempt $i/$maxDownloadAttempts failed: $_"
              if ($i -eq $maxDownloadAttempts) {
                Write-Host "❌ Failed to download custom noVNC"
                exit 1
              }
              Start-Sleep -Seconds 10
            }
          }
        }
      } catch {
        Write-Host "⚠️ Failed to check noVNC package via pip, downloading custom noVNC..."
        $maxDownloadAttempts = 5
        for ($i = 1; $i -le $maxDownloadAttempts; $i++) {
          try {
            Write-Host "📥 Downloading custom noVNC from Cudatto1m (attempt $i/$maxDownloadAttempts)..."
            Remove-Item -Recurse -Force noVNC -ErrorAction SilentlyContinue
            $novncUrl = "https://github.com/Cudatto1m/noVNC-Custom/archive/refs/heads/master.zip"
            Write-Host "🔗 Using URL: $novncUrl"
            $response = Invoke-WebRequest -Uri $novncUrl -OutFile "noVNC.zip" -TimeoutSec 60 -PassThru
            Write-Host "ℹ️ HTTP Status: $($response.StatusCode) $($response.StatusDescription)"
            Expand-Archive -Path "noVNC.zip" -DestinationPath "." -Force
            Move-Item -Path "noVNC-Custom-master" -Destination "noVNC" -Force
            Write-Host "✅ Custom noVNC downloaded and extracted"
            $novncPath = "noVNC"
            break
          } catch {
            Write-Host "⚠️ Custom noVNC download attempt $i/$maxDownloadAttempts failed: $_"
            if ($i -eq $maxDownloadAttempts) {
              Write-Host "❌ Failed to download custom noVNC"
              exit 1
            }
            Start-Sleep -Seconds 10
          }
        }
      }
      
    - name: 🔄 Auto Restart Workflow
      if: always()
      run: |
        $lockFile = "restart.lock"
        $currentTime = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        
        "RESTART_$(Get-Date -Format 'yyyyMMdd_HHmmss')" | Out-File -FilePath $lockFile -Encoding UTF8
        
        Write-Host "🔁 Initiating workflow restart at $currentTime"
        
        try {
          Stop-Process -Name "cloudflared" -Force -ErrorAction SilentlyContinue
          Stop-Process -Name "python" -Force -ErrorAction SilentlyContinue
          Stop-Process -Name "tvnserver" -Force -ErrorAction SilentlyContinue
        } catch {
          Write-Host "⚠️ Process cleanup failed: $_"
        }
        
        Start-Sleep -Seconds 10
        
        try {
          $headers = @{ "Accept" = "application/vnd.github+json"; "Authorization" = "Bearer $env:GITHUB_TOKEN_VPS"; "Content-Type" = "application/json"; "X-GitHub-Api-Version" = "2022-11-28" }
          
          $payload = @{ event_type = "create-vps"; client_payload = @{ vps_name = "vps-project-1757284306519"; restart_time = $currentTime; auto_restart = $true } } | ConvertTo-Json -Depth 2
          
          Invoke-RestMethod -Uri "https://api.github.com/repos/Cudatto1m/vps-project-1757284306519/dispatches" -Method Post -Headers $headers -Body $payload -TimeoutSec 30
          Write-Host "✅ Workflow restart triggered"
          
          git add $lockFile
          git commit -m "🔄 Auto restart - $currentTime" --allow-empty
          git push origin main --force-with-lease
          
        } catch {
          Write-Host "❌ Restart failed: $_"
          Remove-Item $lockFile -Force -ErrorAction SilentlyContinue
          exit 1
        }
